spring.application.name=employee-leave-management

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
app.cors.allowed-origin=${CORS_ORIGIN:http://localhost:4200}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

server.port=${PORT:8080}

app.cors.allowed-origin=${FRONTEND_URL:http://localhost:4200}
